### ISSUE TITLE
Incorrect CurseForge website settings limiting install to 1.18 only so max Forge 38.0.17

### ISSUE THREAD

**Issue by AlcyonNorthstar** [Sajeyson-Dev/Witherproofed#1]
I believe you intend for this mod to be used for all minor versions of 1.18 (currently, max is 1.18.1).  However, some setting on the file on the website is not allowing it to be installed by CurseForge App for anything beyond MC 1.18.0 and Forge 38.0.17.

**Comment by Sajeyson** [comment]
Fixed. Sorry for late response.
