### ISSUE TITLE
WitherProofed causing major issues in server environment

### ISSUE THREAD

**Issue by Zelioth** [Sajeyson-Dev/Witherproofed#2]
Minecraft Version 1.19.2
Forge Version : 43.1.27
WitherProofed Version : 2.7.4

Custom Published Mod Pack and Server Pack : https://www.curseforge.com/minecraft/modpacks/friends-united

Currently testing an update for my mod pack Friends United. I am updating all mods that have updates and adding a few. After updating all the mods and adding I encountered an error where the server would fail to load multiple mods and give no exact reason why. after looking at the log and testing ONE by ONE deleting each mod updated and installed the mod that fixed the issue once removed was WitherProofed version 2.7.4. I reinstalled all mods and  the original version witherproofed (2.7.3) and the new error is Witherproofed failed to load correctly to which I will be uploading the log, the crash report, and the NEW crash report that directly pointed at witherproofed. 
[crash-2022-09-26_00.34.23-fml.txt](https://github.com/Sajeyson-Dev/Witherproofed/files/9643285/crash-2022-09-26_00.34.23-fml.txt)

[crash-2022-09-26_00.46.28-fml.txt](https://github.com/Sajeyson-Dev/Witherproofed/files/9643284/crash-2022-09-26_00.46.28-fml.txt)
[2022-09-26-15.log](https://github.com/Sajeyson-Dev/Witherproofed/files/9643288/2022-09-26-15.log)

**Comment by sajeyson012** [comment]
[Fixed!](https://github.com/Sajeyson-Dev/ShiftedLib/commit/2d3f4c5e21c6faded09ec593a2e43cb94e56eb21) The issue is actually on the ShiftedLib side. New version is already available. 
https://www.curseforge.com/minecraft/mc-mods/shiftedlib/files/all
